site_name: _babe documentation 
nav:
    - Views: 01_views.md
    - Complex experiments: 02_complex.md
    - Server app: 03_server_app.md
    - Deployment: 04_deployment.md
    - Miscellaneous: 05_miscellaneous.md
    - Development: 06_development.md
    - About: 07_about.md
theme: readthedocs
