site_name: _magpie manual
site_description: 'Documentation of _magpie (minimal architecture for the generation of portable interactive experiments)'
site_author: 'Michael Franke'

theme:
  name: material

  logo: assets/logo_small.png
  features:
    #- navigation.instant
    - search.suggest
    - search.highlight

  use_pygments: true

repo_url: https://github.com/magpie-ea/magpie-docs/

nav:
- Home: 'index.md'
- Getting started:
  - Introduction: '00_getting_started/00_intro.md'
  - Installation: '00_getting_started/01_installation.md'
  - Vue.js: '00_getting_started/03_vue_js.md'
  - Basics: '00_getting_started/04_basics.md'
- Designing Experiments:
  - Built-in screens: '01_designing_experiments/00_built-in_screens.md'
  - Custom screens: '01_designing_experiments/01_custom_screens.md'
  - Trial data: '01_designing_experiments/02_trial_data.md'
  - Interactive experiments: '01_designing_experiments/03_interactive_experiments.md'
- Server app:
  - Installation: '02_using_the_server_app/01_installation.md'
  - Use: '02_using_the_server_app/02_use.md'
- Deploying experiments:
  - Deploy configuration: '03_deploying_experiments/01_configuration.md'
  - Recruitment via MTurk: '03_deploying_experiments/02_recruitment_MTurk.md'
  - Recruitment via Prolific: '03_deploying_experiments/03_recruitment_Prolific.md'
  - Hosting on netlify: '03_deploying_experiments/04_hosting_on_netlify.md'
- Misc:
  - Development: 04_development.md
  - About: 05_about.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

copyright: MIT license
