site_name: _magpie manual
site_description: 'Documentation of _magpie (minimal architecture for the generation of portable interactive experiments)'
site_author: 'Michael Franke'

theme:
    # name: rtd-dropdown
    # Default settings
    collapse_by_default: false
    highlightjs: true
    hljs_languages:
        - javascript
        - elixir
    # Development Settings
    name: null
    custom_dir: 'rtd_dropdown/'

repo_url: https://github.com/magpie-ea/magpie-docs/

nav:
- Getting started:
    - Introduction: '00_getting_started/01_intro.md'
    - File structure: '00_getting_started/02_file_structure.md'
    - Vue.js: '00_getting_started/03_vue_js.md'
    - Basics: '00_getting_started/04_basics.md'
- Designing Experiments:
  - Built-in screens: '01_designing_experiments/00_built-in_screens.md'
  - Custom screens: '01_designing_experiments/01_custom_screens.md'
  - Trial data: '01_designing_experiments/02_trial_data.md'
- server app:
  - Installation: '02_using_the_server_app/01_installation.md'
  - Use: '02_using_the_server_app/02_use.md'
- deploying experiments:
  - Deploy configuration: '03_deploying_experiments/01_configuration.md'
  - Recruitment via MTurk: '03_deploying_experiments/02_recruitment_MTurk.md'
  - Recruitment via Prolific: '03_deploying_experiments/03_recruitment_Prolific.md'
  - Hosting on netlify: '03_deploying_experiments/04_hosting_on_netlify.md'
- Misc:
  - Development: 04_development.md
  - About: 05_about.md

plugins:
    - search

copyright: MIT license
markdown_extensions:
    - toc:
        baselevel: 4
